#version for config and support version 18
version: '3.6'

services:

  dbudf:
    image: miguelwill/mariadb-udf-sys:latest
    container_name: dbudf
    restart: always
    volumes:
       - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: passroot
      MYSQL_DATABASE: sitiodb
      MYSQL_USER: sitiouser
      MYSQL_PASSWORD: sitioPass
      TZ: America/Santiago
    ports:
      - 3306:3306
    command:
      --max_allowed_packet=1024M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=0
     - PMA_HOST=dbudf
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
     - phpmyadmin_conf:/usr/local/etc


volumes:
  db-data:
  phpmyadmin_conf:
